name: Dev_build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Wrapper Validation
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: current
          cache-provider: basic

      - name: Build
        run: gradle build
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/*.jar